### ISSUE TITLE
Listed function will not fully show? Also make a windows version and simply modified

### ISSUE THREAD

**Issue by robin840211** [yosh778/NoPayStationGetDLCs#1]
All right, just known my fault and how bad my code is, and my first thought was wrong.
Sorry for open issue and bother.

**Comment by yosh778** [comment]
I don't really see how your list version is any better, I didn't mean to create a CSV-like output but more console-like, not sure how it works on Windows though.
Also obviously my version is mainly Linux oriented but it shouldn't be so hard to get it running from windows.
However on Windows I heard you can use something called NPS Browser so I guess that would be best for most users.
